### ISSUE TITLE
FigmaでUIデザインをする

### ISSUE THREAD

**Issue by kCat-fun** [p2hacks2023/pre-03#13]
# Why
デザイン設計を行い、円滑にフロント開発を進めるため。

# What
Figmaを使用。

**Comment by kCat-fun** [comment]
必要なページのFlameだけ作成した。

**Comment by kCat-fun** [comment]
途中経過![DSC_2876.jpg](https://github.com/p2hacks2023/pre-03/assets/118804479/051bb5f6-372e-437c-8821-320957f2289b)

**Comment by kCat-fun** [comment]
途中経過![DSC_2877.jpg](https://github.com/p2hacks2023/pre-03/assets/118804479/d279fb0d-0f3f-4127-a0c5-4ecdd2a57080)

**Comment by kCat-fun** [comment]
いい感じ![DSC_2878.jpg](https://github.com/p2hacks2023/pre-03/assets/118804479/109a75ba-b85d-4c8c-b296-dca55588be0d)

**Comment by kCat-fun** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/118804479/9ede0766-12b8-4413-a181-a6260862f3ff)

現状

**Comment by kCat-fun** [comment]
「ひんやり」投稿時のポップアップをデザインするの忘れてたので急いでやります。

**Comment by kCat-fun** [comment]
投稿時のGoogle Maps表示がどうなるかわからんので、そのコンポーネントだけいったん保留。
すでに設計終わっていて作れるコンポーネントの作成と、Google Mapsの技術検証をする。

ゲーム画面のデザインもいったん保留でコンポーネントの作成に取り掛かろうと思う
（俺はいったんマーカーの技術検証します）
コンポーネントごとにgithub projectのToDo増やしてissue書いてね！
@イダルゴ 
- PostButton
- GoogleMapButton
- Button
@なにがし 
- InputBox
- OpinionBox
- GoogleAccountButton

Vuetifyにあるものは活用したいから、どれを使うのかリンクをissueに貼ってほしい。
https://vuetifyjs.com/en/components/all/
https://vuetifyjs.com/en/getting-started/wireframes/#examples

分からないとか、出来ない部分があればissueに書いてpushして（commitメッセージにも軽く説明付けて）ほかのコンポーネント作ってほしい

**Comment by uwatcha** [comment]
アカウントを作成するボタンの文字がログイン画面では「新規作成」、サインイン画面では「アカウント作成」、のように文字が違うのは仕様ですか？

**Comment by kCat-fun** [comment]
↑ 別issueで返答済み

**Comment by kCat-fun** [comment]
@p2hacks2023/pre03 

ひんやりのPOST画面どう？
![Image](https://github.com/p2hacks2023/pre-03/assets/118804479/cf48b1b8-9323-4b85-843d-099b3c54bd3c)

**Comment by b1022054** [comment]
ごっつええ

**Comment by kanata0510** [comment]
投稿ボタンの文字が読みにくいので、ボタンの色をもっと濃くしたほうがいいと思う。
画像だと味気ないからひんやりを使ったほうがいいと思う。
Googleマップは動的な部分だからもっと大きく使って、画像選択フォームをウインドウのように表示したほうがいいと思う。

**Comment by kCat-fun** [comment]
@kanata0510 
ちょっと後で相談しよう

**Comment by uwatcha** [comment]
ファイル名の表示いらないんじゃないか
ユーザーはファイル名より画像自体を見るわけだし。
スマホからならなおさらファイル名は意識しないと思う
遅くなってごめん

**Comment by kCat-fun** [comment]
大幅に変更

**Comment by kCat-fun** [comment]
さらに変更

**Comment by uwatcha** [comment]
ごっつええ感じ

**Comment by uwatcha** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/5e125a39-cc51-4122-be6e-3dbc2e1dd61d)

このボタンが真円じゃないのは仕様ですか？一応これに従ってコーディングする。

**Comment by kCat-fun** [comment]
それFigmaの使用上いい感じに中央に寄せれなかったからとりあえずそうしただけで、真円で作ってほしい
（あと、こういう話は各issueの方でお願い）

**Comment by kCat-fun** [comment]
ゲームページは時間の都合上デザイン設計せずに作成することにしたのでClose。
