### ISSUE TITLE
firebase CloudFirestoreを使ってひんやりの情報を消去する

### ISSUE THREAD

**Issue by Ibuki173** [p2hacks2023/pre-03#15]
# WHY

ユーザーが消したいと思ったときに消せるように。また、情報が間違ったときに取り消せるように

# WHAT

firebaseとCloudFirestore

**Comment by kanata0510** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/54180109/38758883-d3b3-495a-a0a3-58015a08f57a)
![Image](https://github.com/p2hacks2023/pre-03/assets/54180109/753a7daf-f74c-489b-94ff-a9a0df9312a2)

**Comment by kanata0510** [comment]
deletedoc関数で消せた
