### ISSUE TITLE
スマホ・端末内のフォルダから画像を取得する

### ISSUE THREAD

**Issue by kanata0510** [p2hacks2023/pre-03#16]
# Why
スマホ、端末本体からアップロードする画像を取得するため。
# What
html input
```html
<input type="file">
```

**Comment by kCat-fun** [comment]
js部分はがんばって

**Comment by kanata0510** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/54180109/1b2c92cd-9f43-4123-84f7-e84278fd257c)

画像アップロードしようとして記事見てたらできた

**Comment by Ibuki173** [comment]
ナイスー。ありがとー。
