### ISSUE TITLE
フロント PostButton作成

### ISSUE THREAD

**Issue by uwatcha** [p2hacks2023/pre-03#21]
# Why
ひんやりしたものの写真、名前、場所を投稿するため
# What
Nuxtで、Vuetifyを用いる

**Comment by uwatcha** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/074d19de-f039-455f-8e5b-c75b98527f37)

とりあえず円の部分はできた。画像の＋は図形ではなく文字なので、これから図形で描画する。

**Comment by kCat-fun** [comment]
@uwatcha 
まだ完成してないならDoneじゃなくね？

**Comment by uwatcha** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/3bca278a-8c9c-46ab-95a6-fe0364a326cf)

完成しました
