### ISSUE TITLE
フロント GoogleMapButton作成

### ISSUE THREAD

**Issue by uwatcha** [p2hacks2023/pre-03#22]
# Why
ひんやりしたものがある場所を調べるためにGoogleMapを開くため。
# What
Nuxtで、Vuetifyを用いる

**Comment by uwatcha** [comment]
https://reffect.co.jp/vue/nuxt3#Nuxt_3-2
このサイトでNuxtを勉強中

**Comment by uwatcha** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/2bdb306b-0d3a-4a64-8aea-d410dfc647f5)

図形が出ないにゃあ
多分何かが違うんだろな

**Comment by uwatcha** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/105820cd-3a86-418d-85c9-2ededab680ac)

AppPageのフォルダが無いから追加する

**Comment by kCat-fun** [comment]
@uwatcha 
まってまって、なくて正常だから、そのままで
色々と言いたいことがあるので通話来て！！

**Comment by uwatcha** [comment]
figma
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/e93081d9-66d7-4f1e-865d-691cdd38011e)

css
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/3d82aea4-d008-4c1e-824a-1d5868931016)

微妙にフォントが違う。これを気にしなくていいのならば完成。

**Comment by kCat-fun** [comment]
フォントはいった無視でOK
（一応同じやつが全部に適応されるようにreset.css書いたのに妙だな..）

**Comment by uwatcha** [comment]
font family: "regular"
って書いてダメだった気がする
figmaでは"regular"って名前になっていた
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/bd4a6313-43ae-48bc-81ad-7de8c56ce76b)

単に書き方が悪いのか、regularって名前はfigma特有なのか
続きは明日

**Comment by kCat-fun** [comment]
@uwatcha 
それはフォント名じゃなくて、太文字とかイタリックとかそういうたぐいの物

**Comment by uwatcha** [comment]
アホでした。フォントは正しいものに修正できました。完全に完成です。
![image](https://github.com/p2hacks2023/pre-03/assets/105112595/abcea12b-df21-43e9-a93a-6e9123aef90f)

**Comment by kCat-fun** [comment]
cssの実装がまずかったので修正
