### ISSUE TITLE
フロント Button作成

### ISSUE THREAD

**Issue by uwatcha** [p2hacks2023/pre-03#23]
# Why
送信、Log in、アカウント作成、新規作成を行うため
# What
Nuxtで、Vuetifyを用いる

**Comment by uwatcha** [comment]
「Button」は、送信、Log in、アカウント作成、新規作成で流用するボタンの背景のことだと解釈した。質問したので返答待ち。

**Comment by uwatcha** [comment]
理解了解感謝無限大

**Comment by kCat-fun** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/118804479/5b2a3f91-b02f-4392-917b-e5c7b6197a92)

作った
