### ISSUE TITLE
フロント GoogleAccountButton作成

### ISSUE THREAD

**Issue by b1022054** [p2hacks2023/pre-03#26]
# Why
Googleアカウントのログイン認証を通すため

# What
Nuxt.jsとVuetifyを組み合わせる

**Comment by b1022054** [comment]
見た目つくってバックエンド渡せる形にしとく

**Comment by kCat-fun** [comment]
@b1022054 
OK！
ただ、js部分は書かなくていいよ
js部分はnameだけ書いておいてくれればOK！

```html
<script>
export default {
    name: 'コンポーネント名'
}
</script>
```

**Comment by b1022054** [comment]
OK!!

**Comment by b1022054** [comment]
これの機能的にイダルゴのButtonのatoms部分を活用する形になりそうなんだよな

**Comment by uwatcha** [comment]
そこらへん金子君に修正してもらったからpushされるの待つべし

**Comment by b1022054** [comment]
ありがとう！！

**Comment by b1022054** [comment]
![Screenshot_20231212-174341](https://github.com/p2hacks2023/pre-03/assets/119466343/48d87463-7a62-4710-a1e6-3e217efe9857)

**Comment by b1022054** [comment]
CSS整えてスマホとパソコンで正常に機能することを確認。
