### ISSUE TITLE
アプリのロゴ作成

### ISSUE THREAD

**Issue by kCat-fun** [p2hacks2023/pre-03#33]
# Why
アプリのロゴが必要だから。

# What
伊吹君ここどうやって作るか変えておいて。

**Comment by kCat-fun** [comment]
@Ibuki173 
スマホ壊れたんだよね？
技術検証は置いておいて、一旦ロゴ作っててほしい。
イメージとしてはこんな感じに、ひんやりとアルバム要素があると良いと思う。


![Image](https://github.com/p2hacks2023/pre-03/assets/118804479/95241727-fb00-4170-9134-3dc0329a85af)

**Comment by Ibuki173** [comment]
# What 
Medi Bang Paint Pro

**Comment by Ibuki173** [comment]
あんまり進んでいないが、組み合わせるパーツはアルバム以外はいい感じにできた

**Comment by kCat-fun** [comment]
@kCat-fun 
今どんな感じ？
進捗状況を書いてほしい。スクショとか。

**Comment by Ibuki173** [comment]
現在タイトル作成。終わったら、ロゴ、熊を順に作成

**Comment by Ibuki173** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/120097886/64af4d0c-84ec-4713-ac8e-abe8fc595e63)

現在迷走中

**Comment by Ibuki173** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/120097886/b8630b96-0fba-4036-98bd-b9df749caaed)

いい感じ

**Comment by Ibuki173** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/120097886/c8453c58-03cd-48a1-9ebd-54db46a84d36)

**Comment by Ibuki173** [comment]
次ロゴに入ります

**Comment by Ibuki173** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/120097886/f9ccad92-82e4-4069-a0d2-7c603c41b825)

まだ仮だけどおいておきます

**Comment by Ibuki173** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/120097886/749b32a9-0338-4219-84be-5c43f393a8f3)

ひんやりアルバムのロゴです。お納めください

**Comment by Ibuki173** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/120097886/f20be64e-cd9e-4f25-811f-44f0ee5015c5)

いったん使えるレベルまで作ったので寝ます。まだいじると思います

**Comment by Ibuki173** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/120097886/0d4b1901-952c-4f04-8da7-af17bca12340)

どっちがいいかみんなで決めよう
