### ISSUE TITLE
フロント CloseButtonを作成

### ISSUE THREAD

**Issue by uwatcha** [p2hacks2023/pre-03#36]
# Why
画面を1つ前に戻すため
# What
Vuetifyを用いてNuxt3で

**Comment by uwatcha** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/3f1e24a3-a2b7-4936-9e8d-c6445afae458)

完成

**Comment by kCat-fun** [comment]
cssの実装がまずかったので修正


![Image](https://github.com/p2hacks2023/pre-03/assets/118804479/dd730340-73d1-4d17-af52-f37787b5a4b5)
