### ISSUE TITLE
FontAwesomeのテスト

### ISSUE THREAD

**Issue by b1022054** [p2hacks2023/pre-03#38]
# Why
リッチなデザインをしたアイコンを使用するため
# What
技術検証する

**Comment by b1022054** [comment]
アカウント作成してHTML版のやつはできそう
ただCSS(SCSS)で書くのが一番理想だと思うから挑戦中

**Comment by kCat-fun** [comment]
NuxtだからVue版のやつでやってほしい

**Comment by b1022054** [comment]
了解

**Comment by b1022054** [comment]
![スクリーンショット 2023-12-13 155057](https://github.com/p2hacks2023/pre-03/assets/119466343/0d6913ef-9bac-4fff-a584-62f3a8df3f4d)

vueでの環境構築と表示が出来た。スマホでも確認。

**Comment by kCat-fun** [comment]
FontawesomeをNuxt3で使うには以下のコマンドが必要
```
npm install @fortawesome/vue-fontawesome@latest
npm install @fortawesome/fontawesome-svg-core
npm install @fortawesome/free-solid-svg-icons
```
