### ISSUE TITLE
フロント TermBox作成

### ISSUE THREAD

**Issue by uwatcha** [p2hacks2023/pre-03#54]
# Why
見栄えのため、利用規約をボックス内に表示するため
# What
Nuxtでコーディングする

**Comment by uwatcha** [comment]
https://kiyaku.jp/hinagata/sns.html
このサイトのひな型を使用する

**Comment by uwatcha** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/6fe20776-97f6-41de-b7a8-3e1cbaa815c3)

ボックス内に表示することができた。

**Comment by uwatcha** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/6c3c63e9-3bdd-4ae3-bba5-dfcecd6e2afe)

現在、利用規約はindex.vueにそのまま書き込んでいるため、テキストファイルに利用規約を記入し、それをindex.vueで呼び出すようにする。

**Comment by uwatcha** [comment]
スクロールバーのデザインがfigmaのものと違い、さらにそのバーがBoxからはみ出ているため、それを今後解決する。

**Comment by uwatcha** [comment]
利用規約の文をひな型をもとに記述する。
ひな型は以下を用いる予定だが、もっと適したものがあるかも
https://kiyaku.jp/hinagata/sns.html

**Comment by uwatcha** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/d1cdd5a0-a9ba-4599-8234-4e9a507a00fb)

ボックス内に規約を表示できた。

**Comment by uwatcha** [comment]
なんとなくjsonの書き方がわかってきたが、画像のように文の中でインデントが起こった場合の書き方に苦戦してる



![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/fb06e43b-1a97-4049-b54d-915e5b22f50f)

**Comment by uwatcha** [comment]
現状
index.vue
<template>
  <div class="box">
    <div class="margin">
      <div v-for="term in terms">
        <div class="heading">
          {{ term.heading }}
        </div>
        <div v-for="term in terms.text">
          {{ term.text.main1 }}
          {{ term.text.indent1 }}
        </div>
        <br/><br/>
      </div>
    </div>
  </div>
</template>

<script>
import term from '../assets/term.json';
export default {
  name: "TermBox",
  data: () => ({
    terms: term,
    texts: term.txt
  })
}
</script>

<style lang="scss" scoped>@import './index.scss';
</style>

term.json
[
    { 
      "text": {"main1": "この利用規約（以下，「本規約」といいます。）は，＿＿＿＿＿（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。"}
    },
    { 
      "heading": "第1条（適用）",
      "text": {"main1": "・本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。\n・当社は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。\n・本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。"}
    },
    {
      "heading": "第2条（利用登録）",
      "text": {
        "main1": "・本サービスにおいては，登録希望者が本規約に同意の上，当社の定める方法によって利用登録を申請し，当社がこの承認を登録希望者に通知することによって，利用登録が完了するものとします。\n・当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。",
        "indent1": "1. 利用登録の申請に際して虚偽の事項を届け出た場合\n2. 本規約に違反したことがある者からの申請である場合\n3. その他，当社が利用登録を相当でないと判断した場合"
    }
    }
]

![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/30bc4e37-144c-412d-a099-e41d4d4151f2)

**Comment by uwatcha** [comment]
時間かかりそうなのでまずはインデント使わずに完成させてみる

**Comment by kCat-fun** [comment]
@uwatcha 
インデントは無しで作ってくれれば最後時間があれば追加する。

子コンポーネントが読めないというのは？

**Comment by kCat-fun** [comment]
やばそうなら、今少し時間あるから対応する

**Comment by uwatcha** [comment]
インデントなしでいいならピンチではない
子コンポーネントじゃなくて、子プロパティが読み込めてない
![image](https://github.com/p2hacks2023/pre-03/assets/105112595/e740b942-335c-41bd-b1ce-9fd2a256be04)
textの中のmainとindentが表示できない

**Comment by kCat-fun** [comment]
@uwatcha 
textの中のmain1とかってこと？

**Comment by uwatcha** [comment]
そう
![image](https://github.com/p2hacks2023/pre-03/assets/105112595/424b4e81-e902-4485-b521-9f07eab91677)
こっちはindent.vueの呼び出しの部分

**Comment by uwatcha** [comment]
![image](https://github.com/p2hacks2023/pre-03/assets/105112595/61619a8b-9337-4b62-b423-45c7a1f99a6b)
headingは見出し、main1は本文、indent1は本文より右にずれてる文

**Comment by uwatcha** [comment]
ボックス削除。利用規約の文完成。以下表示イメージ
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/193e7b2e-7c37-4e23-9509-6bc7a06ebcff)

**Comment by uwatcha** [comment]
<li>を使うことを覚えた
改行記号でなく、文を配列に入れてfor文で回すことにより呼び出す。
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/6387067b-006c-4593-859e-a381e6c02e20)

**Comment by uwatcha** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/433e24f5-d79f-40db-8c5f-51bbc102578b)

インデントで表示できるようになった！
しかし、本文の最後以外のインデントにはまだ非対応

**Comment by uwatcha** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/e6068647-f65e-44eb-8b28-b7459ece7f04)

完成

**Comment by uwatcha** [comment]
![Image](https://github.com/p2hacks2023/pre-03/assets/105112595/0deae772-9b39-41a2-ae0f-4da9e3adfaae)
TermBoxを本文を含めないものとする。Whyを書き替えた。（旧：GoogleMapsで位置情報を扱うため、その使用についてユーザーに同意してもらうため）完成
