### ISSUE TITLE
フロント TermHeading作成

### ISSUE THREAD

**Issue by uwatcha** [p2hacks2023/pre-03#59]
# Why
GoogleMapsで位置情報を扱うため、その使用についてユーザーに同意してもらうため。利用規約のうち見出しを表示する。
# What
Nuxtを用いる

**Comment by b1022054** [comment]
<template>
  <div>
    {{ heading }}
  </div>
  <br>
</template>

<script>
export default {
  name: "TermHeading",
  props: {
    heading: {
      type: String,
      required: true
    }
  }
}
</script>

<style lang="scss" scoped>@import './index.scss';
</style>
